# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75721f3a30f4b96ba0e8c49302d42e07afeb460584923957d65db284fb84c85bbba7f884a4d500e242606b74059f8cf284fd8af90b7e0f29837e88e2be1c05ba

test:
  secret_key_base: 521057bee190ec918a560cab7f1787adb4bfd6ce98d8a9d13b75ecd118bc11c673adc58fd2589a6dcfbdb7f87d2b2f6fbf11ab9f35246d7e5f75e65cb0620590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
